import 'package:flutter/material.dart';
import '../../../core/theme/colors.dart';
class AuthConstants {
 static const String appName = 'Megalopolis';
 static const String appSlogan = 'Your City, One App';
 static const List<Map<String, dynamic>> onboardingSteps = [
  {'title': 'All Your Services\nIn One Place', 'description': 'Food Delivery, Ride Hailing, Shopping, Payments,\nAnd More - All In One Super App', 'icon': Icons.apps_rounded, 'color': AppColors.primary, 'step': '1 Of 3'},
  {'title': 'Secure Payments', 'description': 'Bank-Level Encryption Keeps Your Money\nAnd Data Safe At All Times', 'icon': Icons.security_rounded, 'color': AppColors.success, 'step': '2 Of 3'},
  {'title': 'Fast Delivery', 'description': 'Get Your Orders Delivered In Minutes,\nTrack In Real-Time With Live Updates', 'icon': Icons.rocket_launch_rounded, 'color': AppColors.accent, 'step': '3 Of 3'},
 ];
 static const String defaultUserRole = 'user';
 static const String welcomeBackTitle = 'Welcome Back!';
 static const String loginSubtitle = 'Login To Continue';
 static const String emailLabel = 'Email';
 static const String emailHint = 'your@email.com';
 static const String passwordLabel = 'Password';
 static const String passwordHint = 'Enter Password';
 static const String enterEmailError = 'Please Enter Your Email';
 static const String enterPasswordError = 'Please Enter Your Password';
 static const String forgotPasswordLink = 'Forgot Password?';
 static const String loginButton = 'Login';
 static const String orDivider = 'OR';
 static const String continueWithGoogle = 'Continue With Google';
 static const String continueWithApple = 'Continue With Apple';
 static const String noAccountText = 'Don\'t Have An Account? ';
 static const String signUpButton = 'Sign Up';
 static const String loginFailedPrefix = 'Login Failed: ';
 static const String createAccountTitle = 'Create Account';
 static const String signUpSubtitle = 'Sign Up To Get Started';
 static const String fullNameLabel = 'Full Name';
 static const String fullNameHint = 'John Doe';
 static const String emailHintRegister = 'john@example.com';
 static const String phoneLabel = 'Phone Number';
 static const String phoneHint = '+1 234 567 8900';
 static const String enterNameError = 'Please Enter Your Name';
 static const String enterValidEmailError = 'Please Enter A Valid Email';
 static const String enterPhoneError = 'Please Enter Your Phone Number';
 static const String enterValidPasswordError = 'Please Enter A Password';
 static const String passwordMinLengthError = 'Password Must Be At Least 6 Characters';
 static const String createAccountButton = 'Create Account';
 static const String hasAccountText = 'Already Have An Account? ';
 static const String signInButton = 'Sign In';
 static const String registrationFailedPrefix = 'Registration Failed: ';
 static const String createNewPasswordTitle = 'Create New Password';
 static const String createNewPasswordSubtitle = 'Your New Password Must Be Different From Previously Used Passwords';
 static const String newPasswordLabel = 'New Password';
 static const String confirmPasswordLabel = 'Confirm Password';
 static const String confirmPasswordError = 'Please Confirm Your Password';
 static const String passwordsNoMatchError = 'Passwords Do Not Match';
 static const String resetPasswordButton = 'Reset Password';
 static const String forgotPasswordTitle = 'Forgot Password?';
 static const String forgotPasswordSubtitle = 'Don\'t Worry! Enter Your Email And We\'ll Send You A Reset Link';
 static const String emailAddressLabel = 'Email Address';
 static const String sendResetLinkButton = 'Send Reset Link';
 static const String backToLoginButton = 'Back To Login';
 static const String verifyNumberTitle = 'Verify Your Number';
 static const String verifyNumberSubtitle = 'Enter The 6-Digit Code Sent To\nYour Phone Number';
 static const String resendCodePrefix = 'Resend Code In ';
 static const String resendCodeSuffix = 's';
 static const String resendCodeButton = 'Resend Code';
 static const String verifyButton = 'Verify';
 static const String welcomeToTitle = 'Welcome To\nMegalopolis';
 static const String welcomeSubtitle = 'Everything Your City Has To Offer,\nAll In One Powerful App';
 static const String youreAllSetTitle = 'You\'re All Set!';
 static const String accountCreatedSubtitle = 'Your Account Has Been Created Successfully.\nTime To Explore Megalopolis!';
 static const String startExploringButton = 'Start Exploring';
 static const String checkEmailTitle = 'Check Your Email';
 static const String checkEmailSubtitle = 'We\'ve Sent A Password Reset Link To\nYour Email';
 static const String openEmailAppButton = 'Open Email App';
 static const String resendEmailButton = 'Resend Email';
 static const String secureWithBiometricsTitle = 'Secure With Biometrics';
 static const String biometricsSubtitle = 'Use Fingerprint Or Face ID To Quickly\nAnd Securely Access Your Account';
 static const String enableBiometricsButton = 'Enable Biometrics';
 static const String skipForNowButton = 'Skip For Now';
 static const String enableLocationTitle = 'Enable Location';
 static const String locationSubtitle = 'We Need Your Location To Show You\nNearby Restaurants, Services, And Rides';
 static const String allowLocationButton = 'Allow Location Access';
 static const String getStartedButton = 'Get Started';
 static const String nextButton = 'Next';
 static const String skipButton = 'Skip';
}